### Explicação para a multiplicação de matrizes

link: https://www.somatematica.com.br/emedio/matrizes/matrizes4.php

In [1]:
import tensorflow as tf

tf.__version__

/home/lucas/anaconda3/envs/env_gpu_tf-1.14/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/lucas/anaconda3/envs/env_gpu_tf-1.14/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/lucas/anaconda3/envs/env_gpu_tf-1.14/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/lucas/anaconda3/

'1.14.0'

### Multiplicação de Matrizes com TensorFlow

A multiplicação de matrizes deve obedecer a seguinte regra:
* A quantidade de colunas da primeira matriz da multiplicação deve ser igual a quantidade de linhas da segunda matriz da multiplicação.

Lembrando que a ordem das matrizes na multiplicação afeta o resultado.

**A matriz resultante terá as dimensões com a qtd de linhas da primeira matriz da multiplicação e a qtd de colunas da segunda matriz da multiplicação**.

Caso utilize o operador * ao invés do método matmult() do TensorFlow, não será o mesmo resultado em ambas operações, portanto, **tome cuidado**.

In [2]:
# Definição de matrizes no TF utilizando constantes
a = tf.constant([[1, 2], [3, 4]])
b = tf.constant([[-1, 3], [4, 2]])

In [3]:
# Definição da fórmula para multiplicação de matrizes com TensorFlow
multiplicacao = tf.matmul(a, b)

In [4]:
with tf.Session() as sess:
    print(sess.run(a))
    print('\n')
    print(sess.run(b))
    print('\n')
    print(sess.run(multiplicacao))

[[1 2]
 [3 4]]


[[-1  3]
 [ 4  2]]


[[ 7  7]
 [13 17]]


In [5]:
# É possível fazer a multiplicação da forma inversa definida acima
# porque são matrizes quadradas, ou seja, a qtd de linhas é igual de colunas em ambas
# Portanto, invertendo a ordem da multiplicação não daria problema
# Entretanto, a ordem das matrizes na multiplicação afeta o resultado
multiplicacao2 = tf.matmul(b, a)

In [6]:
with tf.Session() as sess:
    print(sess.run(b))
    print('\n')
    print(sess.run(a))
    print('\n')
    print(sess.run(multiplicacao2))

[[-1  3]
 [ 4  2]]


[[1 2]
 [3 4]]


[[ 8 10]
 [10 16]]


In [7]:
a1 = tf.constant([[2, 3], [0, 1], [-1, 4]])
b1 = tf.constant([[1, 2, 3], [-2, 0, 4]])

# A multiplicação não ocorre erros porque a quantidade de colunas da primeira matriz (a1)
# é igual a quantidade de linhas da segunda matriz (b1)
multiplicacao3 = tf.matmul(a1, b1)

In [10]:
print('Dimensões matriz a1:', a1.shape)
print('Dimensões matriz b2:', b1.shape)

Dimensões matriz a1: (3, 2)
Dimensões matriz b2: (2, 3)


In [8]:
with tf.Session() as sess:
    print(sess.run(a1))
    print('\n')
    print(sess.run(b1))
    print('\n')
    print(sess.run(multiplicacao3))

[[ 2  3]
 [ 0  1]
 [-1  4]]


[[ 1  2  3]
 [-2  0  4]]


[[-4  4 18]
 [-2  0  4]
 [-9 -2 13]]


**A matriz resultante terá as dimensões com a qtd de linhas da primeira matriz da multiplicação e a qtd de colunas da segunda matriz da multiplicação**.