## Placeholders

Os placeholders são de certa forma uma variável que nós atribuimos dados. Eles não são inicializados e eles não contém os dados.

Deve-se definir o tipo de dado que o placeholder irá receber, mas passamos os dados apenas "mais tarde".

Portanto, placeholders são variáveis que receberão dados posteriormente.

`Placeholder` = **Espaço reservado**

In [1]:
import tensorflow as tf

tf.__version__

/home/lucas/anaconda3/envs/env_gpu_tf-1.14/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/lucas/anaconda3/envs/env_gpu_tf-1.14/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/lucas/anaconda3/envs/env_gpu_tf-1.14/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/lucas/anaconda3/

'1.14.0'

Veja que abaixo estamos definindo nosso primeiro `placeholder`.

O primeiro parâmetro que passamos no método placeholder é o tipo de dados que nosso placeholder irá receber.

O segundo parâmetro serão as dimensões dos dados que nosso placeholder irá receber. Quando passamos **None** significa que não sabemos se iremos receber um escalar, vetor, matriz ou tensor.

In [2]:
p = tf.placeholder('float', None)

In [3]:
type(p)

tensorflow.python.framework.ops.Tensor

In [4]:
print(p)

Tensor("Placeholder:0", dtype=float32)


In [5]:
# Definição da fórmula abaixo, sem a sua computação
operacao = p + 2

Para "alimentar" com dados o placeholder, devemos utilizar o parâmetro `feed_dict` e passar a chave como sendo o nome do placeholder e os dados.

Isso tudo deve ser feito em uma sessão inicializada.

In [6]:
with tf.Session() as sess:
    # sess.run(operacao)  se executarmos sem passar os dados do placeholder será retornado erro
    resultado = sess.run(operacao, feed_dict = {p: [1, 2, 3]})
    print(resultado)

[3. 4. 5.]


Observe que abaixo estamos criando nosso segundo `placeholder`.

A diferença do primeiro é que "sabemos" que iremos receber uma **matriz**. Entretanto, não sabemos quantas linhas nossos dados terão, mas sabemos que serão 5 colunas, por isso passamos `[None, 5]`.

In [7]:
p2 = tf.placeholder('float', [None, 5])

operacao2 = p2 * 5

In [8]:
with tf.Session() as sess:
    dados = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
    resultado = sess.run(operacao2, feed_dict={p2: dados})
    print(resultado)

[[ 5. 10. 15. 20. 25.]
 [30. 35. 40. 45. 50.]]
