In [1]:
import tensorflow as tf

tf.__version__

/home/lucas/anaconda3/envs/env_gpu_tf-1.14/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/lucas/anaconda3/envs/env_gpu_tf-1.14/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/lucas/anaconda3/envs/env_gpu_tf-1.14/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/lucas/anaconda3/

'1.14.0'

In [23]:
a = tf.constant([9, 8, 7], name = 'a')
b = tf.constant([1, 2, 3], name = 'b')

### Adição de vetores com TensorFlow

A adição de vetores requer que o tamanho das dimensões dos vetores sejam iguais, caso contrário será retornado um erro no momento da definição da fórmula da soma.

In [24]:
# Define apenas o grafo/fórmula (não computa o cálculo)
soma = a + b

In [22]:
type(a)

tensorflow.python.framework.ops.Tensor

In [5]:
print(a)

Tensor("a:0", shape=(3,), dtype=int32)


In [6]:
# Criando sessão para computar a definição da fórmula/grafo acima
with tf.Session() as sess:
    print(sess.run(soma))

[10 10 10]


Obs: Perceba que a soma de dois vetores é feita entre:
* (a1 + b1), (a2 + b2), (a3 + b3)

In [7]:
# Definição de uma constante que recebe valores de uma matriz
a1 = tf.constant([[1, 2, 3], [4, 5, 6]], name = 'a1')

In [8]:
type(a1)

tensorflow.python.framework.ops.Tensor

In [10]:
# Perceba o shape, agora ele tem o valor shape(2, 3), ou seja, possui
# valores em 2 dimensões, portanto, é uma matriz, onde cada lista é uma linha e a quantidade de elementos de uma lista serão as colunas
print(a1)

Tensor("a1:0", shape=(2, 3), dtype=int32)


In [12]:
# É possível utilizar o atributo shape
a1.shape

TensorShape([Dimension(2), Dimension(3)])

In [25]:
# Definição de uma constante que recebe valores de uma matriz
b1 = tf.constant([[1, 2, 3], [4, 5, 6]], name = 'b1')

### Adição de matrizes com TensorFlow

In [26]:
# Podemos utilizar o método add() do TensorFlow para somar matrizes
soma1 = tf.add(a1, b1)

In [16]:
with tf.Session() as sess:
    print(sess.run(a1))     # exibe a matriz a1
    print('\n')             # pula linha
    print(sess.run(b1))     # exibe a matriz b1
    print('\n')             # pula linha
    print(sess.run(soma1))  # computa a soma definida anteriormente

[[1 2 3]
 [4 5 6]]


[[1 2 3]
 [4 5 6]]


[[ 2  4  6]
 [ 8 10 12]]


Da mesma forma como acontece com a soma de vetores, na soma das matrizes é feita a soma dos elementos que estão na mesma posição.

In [29]:
a2 =tf.constant([[1, 2, 3], [4, 5, 6]])
b2 = tf.constant([[1], [2]])

soma2 = tf.add(a2, b2)

In [30]:
with tf.Session() as sess:
    print(sess.run(a2))
    print('\n')
    print(sess.run(b2))
    print('\n')
    print(sess.run(soma2))

[[1 2 3]
 [4 5 6]]


[[1]
 [2]]


[[2 3 4]
 [6 7 8]]


Perceba que no exemplo acima, as matrizes possuem dimensões diferentes uma da outra. 

Entretanto, ambas possuem a mesma quantidade de linhas, desta forma é possível realizar a soma das matrizes.